### ISSUE TITLE
Further Usage Info

### ISSUE THREAD

**Issue by purplespider** [maleadt/tado-charts#1]
I'm a newbie to virtualenv, but have got it and this module installed fine. Could just do with some elaboration on the 3 usage steps if possible?

**Comment by maleadt** [comment]
Well, those steps in the usage documentation depend on your system/OS, so I can't really detail them much more. But for some more details on how I've set it up:

1) copy the sample `private.py.sample` to `private.py`, and edit it with your details: username/password, name of the home, and array with zones to generate charts for. And crucially, add your MySQL connection details (the table will be created upon first run).
2) run `collect.py` and `plot.py` according to a certain schema. For example, I have two scripts in the root check-out of this repository:

`cron1.sh`:

```sh
#!/bin/bash -ue

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYTHON=$ROOT/env/bin/python3

$PYTHON $ROOT/bin/collect.py
```

`cron5.sh`:

```sh
#!/bin/bash -ue

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYTHON=$ROOT/env/bin/python3

$PYTHON $ROOT/bin/plot.py
mv $ROOT/bin/*.png /var/www/tado   # adjust accordingly
```

Then I've set-up `cron` like this:

```
*   * * * *   /home/tim/tado/cron1.sh
*/5 * * * *   /home/tim/tado/cron5.sh
```

**Comment by purplespider** [comment]
Much appreciated, thank you!
